version: '3'
services:

  nginx:
    container_name: 'nginx'
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app

  app:
    container_name: 'php'
    build: docker/php
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"
      APP_SECRET: "95b54fb4f0a5924b1c7da95f513becb5"
      DATABASE_URL: "pgsql://app:app@database/app"
      TELEGRAM_TOKEN: ""

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
    ports:
      - "5439:5432"  
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
