version: '3'
services:

  nginx:
    container_name: 'nginx'
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app

  app:
    container_name: 'php'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        WITH_XDEBUG: "1"
    volumes:
      - ./:/var/www/app
    depends_on:
      - redis
      - database
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"
      APP_SECRET: "95b54fb4f0a5924b1c7da95f513becb5"
      DATABASE_URL: "pgsql://app:app@database/app"
      TELEGRAM_TOKEN: ""
      REDIS_HOST: "tcp://redis:6379"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
      PHP_IDE_CONFIG: "serverName=symfony-app"

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
    ports:
      - "5439:5432"  
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data

volumes:
  database_data:
  redis:
