# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    
    env(TELEGRAM_TOKEN): ''
    env(REDIS_HOST): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            Psr\SimpleCache\CacheInterface: '@Symfony\Component\Cache\Psr16Cache'
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Exception/'
            - '../src/Http/'
            - '../src/UseCase/**/Query.php'
            - '../src/GraphQL/Error/'
            - '../src/GraphQL/Security/'
            - '../src/GraphQL/UseCase/**/Query.php'
            - '../src/GraphQL/UseCase/**/Command.php'
            - '../src/GraphQL/Context.php'
    
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Backoffice\:
        resource: '../src/Backoffice/'
        exclude:
            - '../src/Backoffice/Entity/'      

    App\Customer\:
        resource: '../src/Customer/'
        exclude:
            - '../src/Customer/Entity/'

    App\IntegrationAPI\:
        resource: '../src/IntegrationAPI/'
        exclude:
            - '../src/IntegrationAPI/Entity/'
            
    App\Command\Telegram\TelegramGenerateButtonsCommand:
        arguments: 
            - '%env(TELEGRAM_TOKEN)%'
    
    App\GraphQL\:
        resource: '../src/GraphQL'
        public: true
        exclude:
            - '../src/GraphQL/TypeRegistry.php'
            - '../src/GraphQL/Context.php'
            - '../src/GraphQL/Dto/'
            - '../src/GraphQL/Type/Dto/'
            - '../src/GraphQL/Error/'
            - '../src/GraphQL/Security/'
            - '../src/GraphQL/UseCase/'
            - '../src/GraphQL/Helper/'
            - '../src/GraphQL/Helper/'
            
    # Redis
                
    Predis\Client:
        arguments:
            - '%env(REDIS_HOST)%'

    Symfony\Component\Cache\Adapter\RedisAdapter:
        arguments:
            - '@Predis\Client'

    Symfony\Component\Cache\Psr16Cache:
        arguments:
            - '@Symfony\Component\Cache\Adapter\RedisAdapter'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Http\RequestResolver\RequestDtoResolver:
        tags:
            -   name: controller.argument_value_resolver
                priority: 50
