# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Exception/'
            - '../src/Http/'
            - '../src/UseCase/**/Query.php'
            - '../src/GraphQL/Error/'
            - '../src/GraphQL/Security/'
            - '../src/GraphQL/UseCase/**/Query.php'
            - '../src/GraphQL/UseCase/**/Command.php'
            - '../src/GraphQL/Context.php'
    
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Backoffice\:
        resource: '../src/Backoffice/'
        exclude:
            - '../src/Backoffice/Entity/'

    App\Customer\:
        resource: '../src/Customer/'
        exclude:
            - '../src/Customer/Entity/'

    App\IntegrationAPI\:
        resource: '../src/IntegrationAPI/'
        exclude:
            - '../src/IntegrationAPI/Entity/'
    
    App\GraphQL\:
        resource: '../src/GraphQL'
        public: true
        exclude:
            - '../src/GraphQL/TypeRegistry.php'
            - '../src/GraphQL/Context.php'
            - '../src/GraphQL/Dto/'
            - '../src/GraphQL/Type/Dto/'
            - '../src/GraphQL/Error/'
            - '../src/GraphQL/Security/'
            - '../src/GraphQL/UseCase/'
            - '../src/GraphQL/Helper/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
